author: "Tobe O <thosakwe@gmail.com>"
description: "Dart bindings for the VSCode API."
environment:
  sdk: ">=1.19.0"
homepage: "https://github.com/thosakwe/dart_vscode.git"
name: "vscode"
version: "1.0.0"
dependencies: 
  js: "^0.6.1"
